var starmapConfig = {},
  starmapUpdateDelay = 0,
  font = 'Montserrat',
  floatVals = [
    'circular',
    'grid',
    'lat',
    'lng',
    'milkyway',
    'names',
    'timezone_offset',
    'floatVals',
  ],
  starmapUpdateTime;
var k_diff = 4.5,
  k_diff_map = 2;
export const config = {
  width: 0,
  projection: 'stereographic',
  center: null,
  orientationfixed: true,
  background: { fill: '#000000', stroke: 'transparent', opacity: 0 },
  adaptable: false,
  interactive: false,
  form: false,
  location: false,
  controls: true,
  lang: '',
  container: 'celestial-map',
  // datapath: url + '/themes/yoma/assets/data/',
  datapath: 'https://ofrohn.github.io/data/',
  stars: {
    show: true,
    limit: 7,
    colors: false,
    style: { fill: '#ffffff', opacity: 1 },
    names: false,
    proper: false,
    desig: true,
    namelimit: 4,
    namestyle: {
      fill: '#ffffff',
      font: '22px ' + font,
      align: 'left',
      baseline: 'top',
    },
    propernamestyle: {
      fill: '#ffffff',
      font: ((30 / k_diff) * 2) / k_diff_map + 'px ' + font,
      align: 'right',
      baseline: 'bottom',
    },
    propernamelimit: 1.5,
    size: 5,
    exponent: -0.2,
    data: 'stars.6.json',
  },
  dsos: {
    show: false,
    limit: 6,
    names: false,
    desig: false,
    namelimit: 4,
    namestyle: {
      fill: '#cccccc',
      font: '11px ' + font,
      align: 'left',
      baseline: 'top',
    },
    size: null,
    exponent: 1.4,
    data: 'dsos.bright.json',
    symbols: {
      gg: { shape: 'circle', fill: '#ff0000' },
      g: { shape: 'ellipse', fill: '#ff0000' },
      s: { shape: 'ellipse', fill: '#ff0000' },
      s0: { shape: 'ellipse', fill: '#ff0000' },
      sd: { shape: 'ellipse', fill: '#ff0000' },
      e: { shape: 'ellipse', fill: '#ff0000' },
      i: { shape: 'ellipse', fill: '#ff0000' },
      oc: { shape: 'circle', fill: '#ffcc00', stroke: '#ffcc00', width: 1.5 },
      gc: { shape: 'circle', fill: '#ff9900' },
      en: { shape: 'square', fill: '#ff00cc' },
      bn: { shape: 'square', fill: '#ff00cc', stroke: '#ff00cc', width: 2 },
      sfr: { shape: 'square', fill: '#cc00ff', stroke: '#cc00ff', width: 2 },
      rn: { shape: 'square', fill: '#00ooff' },
      pn: { shape: 'diamond', fill: '#00cccc' },
      snr: { shape: 'diamond', fill: '#ff00cc' },
      dn: { shape: 'square', fill: '#999999', stroke: '#999999', width: 2 },
      pos: { shape: 'marker', fill: '#cccccc', stroke: '#cccccc', width: 1.5 },
    },
  },
  constellations: {
    show: false,
    names: false,
    desig: false,
    namestyle: {
      fill: '#cccc99',
      align: 'center',
      baseline: 'middle',
      opacity: 0.8,
      font: ['bold 14px ' + font, 'bold 12px ' + font, 'bold 11px ' + font],
    },
    lines: true,
    linestyle: {
      // stroke: '#309000',
      stroke: '#f8f9fa',
      width: 1,
      opacity: 0.9,
    },
    bounds: false,
    boundstyle: { stroke: '#cccc00', width: 1, opacity: 0.8, dash: [2, 4] },
  },
  mw: { show: false, style: { fill: '#ffffff', opacity: '0.15' } },
  lines: {
    graticule: {
      show: false,
      // stroke: '#553333',
      stroke: '#6c757d',
      width: 0.9,
      opacity: 0.95,
      lon: { pos: ['center'], fill: '#eee', font: '0px ' + font },
      lat: { pos: ['center'], fill: '#eee', font: '0px ' + font },
    },
    equatorial: { show: !1, stroke: '#aaaaaa', width: 1.3, opacity: 0.7 },
    ecliptic: { show: !1, stroke: '#66cc66', width: 1.3, opacity: 0.7 },
    galactic: { show: !1, stroke: '#cc6666', width: 1.3, opacity: 0.7 },
    supergalactic: { show: !1, stroke: '#cc66cc', width: 1.3, opacity: 0.7 },
  },
};
